// <auto-generated />
using System;
using DaLove_Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DaLove_Server.Data.Migrations
{
    [DbContext(typeof(DaLoveDbContext))]
    [Migration("20211107083807_SwitchUserProfilePkToUniqueName")]
    partial class SwitchUserProfilePkToUniqueName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DaLove_Server.Data.Domain.UserMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemoryFriendlyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoryUniqueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("DaLove_Server.Data.Domain.UserProfile", b =>
                {
                    b.Property<string>("UniqueUserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UserMemoryId")
                        .HasColumnType("int");

                    b.HasKey("UniqueUserName");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserMemoryId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("DaLove_Server.Data.Domain.UserProfile", b =>
                {
                    b.HasOne("DaLove_Server.Data.Domain.UserMemory", null)
                        .WithMany("Recipients")
                        .HasForeignKey("UserMemoryId");
                });

            modelBuilder.Entity("DaLove_Server.Data.Domain.UserMemory", b =>
                {
                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
