// <auto-generated />
using DaLove_Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DaLove_Server.Data.Migrations
{
    [DbContext(typeof(DaLoveDbContext))]
    [Migration("20211107120103_MemoryUniqueNameIsUnique")]
    partial class MemoryUniqueNameIsUnique
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DaLove_Server.Data.Domain.UserMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemoryFriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoryUniqueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemoryUniqueName")
                        .IsUnique();

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("DaLove_Server.Data.Domain.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastKnownFcmDeviceToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("UniqueUserName")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("UserMemoryUserProfile", b =>
                {
                    b.Property<int>("MemoriesId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientsUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MemoriesId", "RecipientsUserId");

                    b.HasIndex("RecipientsUserId");

                    b.ToTable("UserMemoryUserProfile");
                });

            modelBuilder.Entity("UserMemoryUserProfile", b =>
                {
                    b.HasOne("DaLove_Server.Data.Domain.UserMemory", null)
                        .WithMany()
                        .HasForeignKey("MemoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaLove_Server.Data.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("RecipientsUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
