on: 
    workflow_dispatch:
        branches: 
            master
            
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: production
        
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: App Settings Variable Substitution
          uses: microsoft/variable-substitution@v1
          with:
            files: 'DaLove-Server/appsettings.json'
          env:
            KeyVaultOptions.KeyVaultUri: ${{ secrets.AZURE_KEY_VAULT_URI }}
        
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . --file DaLove-Server/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/dalove-master:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dalove-master:${{ github.sha }}
